### ISSUE TITLE
Parsing of do-not-echo at symbol not quite right

### ISSUE THREAD

**Issue by cmungall** [evoldoers/biomake#35] opened 2016-12-29 23:42 UTC
this works in make and biomake:

```
foo:
    @echo hello
```

the effect is not to echo the echo command.

however, that evol-doer @fbastian has come up with a cunning recipe that stymies biomake:

https://github.com/obophenotype/developmental-stage-ontologies/blob/97fa5b7e176f8c7f72cd5c7115d2fc36f35e8bb3/src/Makefile#L16-L17

**Comment by cmungall** [comment] 2016-12-30 00:04
It turns out that's a bit of a funny recipe, see https://github.com/obophenotype/developmental-stage-ontologies/issues/46

but we should still try and ensure biomake has the same behavior as make

**Comment by cmungall** [comment] 2016-12-30 00:11
Here is a simpler example for replication purposes:

```
X=a b c d
test:
	$(foreach o, $(X), @echo $o )
```

running with make:

```
a @echo b @echo c @echo d
```

with biomake:

```
 @echo a   @echo b   @echo c   @echo d 
sh: @echo: command not found
While building test: Error 127 executing  @echo a   @echo b   @echo c   @echo d 
```

the issue is that the `@` is hidden due to being wrapped inside a make function

I'm happy for this to be closed as won't-fix as it's an odd edge-case, I'm having trouble thinking of a genuine case where you would want to wrap the command inside a function, just wanted to report as an edge case.

**Comment by ihh** [comment] 2016-12-30 21:07
At first I thought this was due to the `foreach` function wrapping the `@` modifier, since late expansion of variables & functions does indeed cause some subtle differences, as referenced here https://github.com/evoldoers/biomake#other-differences-from-gnu-make

However, it turned out this was a much simpler bug due to Biomake not recognizing modifiers such as `@` if they are preceded by whitespace. An even simpler test reproducing this would be to put an extra whitespace character before the `@echo foo` in your first example, and (though I haven't tested this) I think the problem would go away if you removed the space between the comma and the `@echo $o` in the simple replication example.

Anyway, have now fixed and am committing the fix, with a test.

**Closed** 2016-12-30 21:08 UTC
Labels: GNU make compatibility
