### ISSUE TITLE
Backslashes in dependencies make biomake sad

### ISSUE THREAD

**Issue by sjackman** [evoldoers/biomake#44] opened 2017-08-31 18:04 UTC
# Makefile
```Makefile
all: a \
	b

a b:
	touch $@
```

# Observed output
```
❯❯❯ biomake
# Target all not materialized - build required
all FAILED
```

# Expected output
```
❯❯❯ make
touch a
touch b
```

**Comment by sjackman** [comment] 2017-08-31 18:05
Thanks for this fantastic tool! The multiple pattern rules are the best.

**Comment by cmungall** [comment] 2017-08-31 18:20
Thanks for the feedback!

I can't seem to recreate this, but it may be the case that github is doing some kind of whitespace replacement.

```
xxd Makefile 
0000000: 616c 6c3a 2061 205c 0a09 620a 0a61 2062  all: a \..b..a b
0000010: 3a0a 0974 6f75 6368 2024 400a            :..touch $@.
```

```
biomake
 touch a
 touch b
Target all not materialized - build required
all built
```

Weirdly, I thought I hit on some combination of spaces and tabs that recreated your output but I carelessly lost that iteration, now I can't seem to reproduce it at all.

**Comment by sjackman** [comment] 2017-08-31 22:54
Our Makefile are identical.
```
❯❯❯ xxd Makefile
0000000: 616c 6c3a 2061 205c 0a09 620a 0a61 2062  all: a \..b..a b
0000010: 3a0a 0974 6f75 6368 2024 400a            :..touch $@.
❯❯❯ biomake
# Target all not materialized - build required
all FAILED
```
I'm using biomake 0.1.1 installed using Homebrew on macOS and Linuxbrew on Linux. I can replicate the issues on both operating systems.
```
❯❯❯ brew install homebrew/science/biomake
❯❯❯ biomake --version | head -n1
Biomake 1.0
```
I've just tested master with `brew upgrade --HEAD biomake`, and the bug is fixed there. Would you please consider tagging and releasing a new version of biomake?

I've noticed now that the output of `biomake --version` is inconsistent with the GitHub tag.

**Comment by sjackman** [comment] 2017-08-31 22:55
Thanks for your quick response!

**Comment by cmungall** [comment] 2017-09-25 19:47
OK I made a release https://github.com/evoldoers/biomake/releases/tag/v0.1.2

So this should work in the brew file:
https://github.com/evoldoers/biomake/archive/v0.1.2.tar.gz 

What next? Do I make a PR on? Looks like you know more about this than I...
https://github.com/Homebrew/homebrew-science/blob/master/biomake.rb

**Comment by sjackman** [comment] 2017-09-25 23:29
Thanks! Yes, you can open a PR. You only have to change the `url` and `sha256` lines.
https://github.com/Homebrew/homebrew-science/blob/master/biomake.rb#L4-L5

**Comment by sjackman** [comment] 2017-11-29 01:53
I've found another case of this issue.

```Makefile
all: \
	a \
	b

a b:
	touch $@
```

```
❯❯❯ biomake
Exception: error(syntax_error(GNU makefile parse error at line 1 of file foo.mk: all:  	a  	b),_1624)
```

**Comment by sjackman** [comment] 2018-01-16 19:58
@cmungall Do you think you'd have time to fix this issue? I'd appreciate your effort very much!

**Comment by cmungall** [comment] 2018-01-16 20:43
Not sure if @ihh has time, I will try and take a look later this week

**Comment by ihh** [comment] 2018-01-16 20:54
It will be in the GNU Makefile parsing code. I will look tomorrow - sorry for the delay

**Comment by sjackman** [comment] 2018-01-16 22:33
No worries, Ian. Thanks a bunch!

**Comment by sjackman** [comment] 2018-01-16 23:38
I commented on a bunch of issues just now. The ones that are really holding me back are…
1. #44 Backslashes in dependencies
2. #49 SLURM
3. #50 Export environment variables

**Closed** 2018-01-17 20:26 UTC

**Comment by sjackman** [comment] 2018-01-17 21:18
Thank you, Ian! 🏆
